In [1]:
import json
import numpy as np
from scipy.spatial.distance import pdist
import random
from sklearn.model_selection import train_test_split

import math
import torch
from netCDF4 import Dataset
from torchvision import datasets
import gpytorch



import math
with open('../Configs/config.json') as f:
  config = json.loads(f.read())
import random


nodesbounds = config['config']['grid_search']["hiddenlayer_size"]
layerbounds = config['config']['grid_search']["hiddenlayer_number"]
learningrate = config['config']['grid_search']["learning_rates"]
batchsize = config['config']['grid_search']['batch_size']


nodes = [i for i in range(nodesbounds[0],nodesbounds[1]+nodesbounds[2],nodesbounds[2])]
layers = [i for i in range(layerbounds[0],layerbounds[1]+layerbounds[2],layerbounds[2])]


## Global bounds on hyper parameters
nbound = len(nodes)
lbound =len(layers) 
ebound = len(learningrate) 
bbound = len(batchsize) 


upperbounds = [nbound,lbound,ebound,bbound]
lowerbounds = [0,0,0,0]

targetsimple = [14,12,2,2]
lowesterror = 100
searchlog = {}

print(upperbounds)



[10, 10, 5, 5]


In [8]:

database =config['config']["database"]["file"]
print(database)

data = Dataset(database, mode='r')
if config['config']["database"]["crdmode"] == "cartesian":
    dbset = np.copy(data['crd'])
    coordinatesout = []
    for j,i in enumerate(dbset):
        if j == 0:
            coordinatesout = [pdist(i)]
        else:
            coordinatesout = np.concatenate((coordinatesout,[pdist(i)]))
            
energyout =np.copy(data['energy'])-np.amin(data['energy'])     
print(coordinatesout)
print(energyout)


coordinates, val_coordinates, output, val_output = train_test_split(coordinatesout, energyout , test_size=config['config']['grid_search']['validation_ratio'])

print(f" output is {output} ")  
print(f" validation output is {val_output}")
print(f" coordinates is {coordinates}")
print(f" validation coordinates {val_coordinates}")




db.dat
[[2.77941757 2.76440917 4.84697076]
 [2.76698152 2.76900611 4.83948085]
 [2.75691651 2.77593716 4.83429377]
 [2.74938863 2.78508657 4.83143719]
 [2.74453164 2.79630852 4.83089482]
 [2.74244372 2.80942972 4.83260669]
 [2.7431851  2.82425238 4.83647096]
 [2.74677709 2.8405571  4.84234703]
 [2.75320254 2.85810566 4.8500602 ]
 [2.76240746 2.87664359 4.85940741]
 [2.77430386 2.89590254 4.87016427]]
[[1.30026000e-05 1.38476884e-01 1.58162384e-01]
 [0.00000000e+00 1.39150584e-01 1.58955644e-01]
 [2.89870001e-05 1.39480344e-01 1.59147334e-01]
 [8.40001001e-05 1.39443554e-01 1.58714964e-01]
 [1.63652300e-04 1.39037264e-01 1.57668304e-01]
 [2.81846500e-04 1.38279024e-01 1.56049534e-01]
 [4.67269800e-04 1.37206234e-01 1.53931434e-01]
 [7.61541000e-04 1.35874014e-01 1.51413464e-01]
 [1.21603860e-03 1.34351604e-01 1.48616114e-01]
 [1.88761530e-03 1.32717424e-01 1.45673914e-01]
 [2.83360780e-03 1.31053354e-01 1.42727624e-01]]
 output is [[2.89870001e-05 1.39480344e-01 1.59147334e-01]
 [2.8336

In [3]:
#test get offspring


In [4]:
## test full routine
