In [1]:
import json 
from netCDF4 import Dataset
import numpy as np
from scipy.spatial.distance import pdist
import random
from sklearn.model_selection import train_test_split
import NeuralNetwork
from GeneticAlgorithm import GeneticAlgorithm

import math 
with open('configGA.json') as f:
  print(f)
  config = json.loads(f.read())
import random

print(config)

<_io.TextIOWrapper name='configGA.json' mode='r' encoding='UTF-8'>
{'config': {'debug': 'on', 'database': {'file': 'db.dat', 'properties': ['energy', 'gradient'], 'crdmode': 'cartesian', 'timestamp': '2021-04-23T18:25:43.511Z', 'mode': 'ab-initio', 'ab-initio': {'exe': 'QChem.exe', 'chg': 0, 'mult': 1, 'exchange': 'pbe0', 'basis': 'cc-pvdz', 'max_scf_cycles': 500, 'xc_grid': '000075000302', 'mem_static': 4000, 'mem_total': 16000, 'sym_ignore': True, 'set_iter': 50, 'input_bohr': True}}, 'neural_network': {'epochs': 200, 'epoch_step': 50, 'logging_file': 'logfile.txt', 'plotting_file': 'plottingfile.txt', 'optimizer': 'adam', 'activation': 'tanh', 'loss_function': 'MSE', 'model_filename': 'Network.pt'}, 'genetic_algorithm': {'hiddenlayer_size': [10, 200, 10], 'validation_ratio': 0.1, 'hiddenlayer_number': [1, 20, 1], 'learning_rates': [1, 0.1, 0.01, 0.001, 0.0001], 'batch_size': [32, 64, 128, 256, 512], 'mutation_rate': 0.1, 'iterations': 2000, 'population_size': 6}}}


In [2]:

lowest_error, best_network = math.inf, None
sizebounds = config['config']['genetic_algorithm']['hiddenlayer_size']
layerbounds = config['config']['genetic_algorithm']['hiddenlayer_number']
learningbounds = config['config']['genetic_algorithm']['learning_rates']


print(random.randint(sizebounds[0],sizebounds[1]))
print(random.choice(learningbounds))

#for n in range(self.config['config']['simulated_annealing']['iterations']) :

    



70
0.1


In [3]:
database = 'db.dat'
data = Dataset(database, mode='r')
if config['config']["database"]["crdmode"] == "cartesian":
    dbset = np.copy(data['crd'])
    coordinatesout = []
    for j,i in enumerate(dbset):
        if j == 0:
            coordinatesout = [pdist(i)]
        else:
            coordinatesout = np.concatenate((coordinatesout,[pdist(i)]))
            
energyout =np.copy(data['energy'])-np.amin(data['energy'])     
print(coordinatesout)
print(energyout)



[[2.77941757 2.76440917 4.84697076]
 [2.76698152 2.76900611 4.83948085]
 [2.75691651 2.77593716 4.83429377]
 [2.74938863 2.78508657 4.83143719]
 [2.74453164 2.79630852 4.83089482]
 [2.74244372 2.80942972 4.83260669]
 [2.7431851  2.82425238 4.83647096]
 [2.74677709 2.8405571  4.84234703]
 [2.75320254 2.85810566 4.8500602 ]
 [2.76240746 2.87664359 4.85940741]
 [2.77430386 2.89590254 4.87016427]]
[[1.30026000e-05 1.38476884e-01 1.58162384e-01]
 [0.00000000e+00 1.39150584e-01 1.58955644e-01]
 [2.89870001e-05 1.39480344e-01 1.59147334e-01]
 [8.40001001e-05 1.39443554e-01 1.58714964e-01]
 [1.63652300e-04 1.39037264e-01 1.57668304e-01]
 [2.81846500e-04 1.38279024e-01 1.56049534e-01]
 [4.67269800e-04 1.37206234e-01 1.53931434e-01]
 [7.61541000e-04 1.35874014e-01 1.51413464e-01]
 [1.21603860e-03 1.34351604e-01 1.48616114e-01]
 [1.88761530e-03 1.32717424e-01 1.45673914e-01]
 [2.83360780e-03 1.31053354e-01 1.42727624e-01]]


In [4]:
coordinates, val_coordinates, output, val_output = train_test_split(coordinatesout, energyout , test_size=config['config']['genetic_algorithm']['validation_ratio'])

print(output,val_output)
print(coordinates, val_coordinates)


[[2.89870001e-05 1.39480344e-01 1.59147334e-01]
 [1.21603860e-03 1.34351604e-01 1.48616114e-01]
 [2.81846500e-04 1.38279024e-01 1.56049534e-01]
 [1.88761530e-03 1.32717424e-01 1.45673914e-01]
 [8.40001001e-05 1.39443554e-01 1.58714964e-01]
 [2.83360780e-03 1.31053354e-01 1.42727624e-01]
 [1.63652300e-04 1.39037264e-01 1.57668304e-01]
 [0.00000000e+00 1.39150584e-01 1.58955644e-01]
 [1.30026000e-05 1.38476884e-01 1.58162384e-01]] [[0.00046727 0.13720623 0.15393143]
 [0.00076154 0.13587401 0.15141346]]
[[2.75691651 2.77593716 4.83429377]
 [2.75320254 2.85810566 4.8500602 ]
 [2.74244372 2.80942972 4.83260669]
 [2.76240746 2.87664359 4.85940741]
 [2.74938863 2.78508657 4.83143719]
 [2.77430386 2.89590254 4.87016427]
 [2.74453164 2.79630852 4.83089482]
 [2.76698152 2.76900611 4.83948085]
 [2.77941757 2.76440917 4.84697076]] [[2.7431851  2.82425238 4.83647096]
 [2.74677709 2.8405571  4.84234703]]


In [5]:
#if (any(i == 'simulated_annealing' for i in config['config'])):
#    if (any(j == 'neural_network' for j in config['config'])):
#        optimizer = SimulatedAnnealing(config,coordinates,  output,val_coordinates, val_output)
#        optimizer.run()

if (any(i == 'genetic_algorithm' for i in config['config'])):
    if (any(j == 'neural_network' for j in config['config'])):
        optimizer = GeneticAlgorithm(config,coordinates,  output,val_coordinates, val_output)
        optimizer.run()
        
        
        

Current population is: [[2, 11, 1, 1], [5, 1, 0, 1], [3, 16, 2, 0], [6, 1, 2, 1], [12, 15, 3, 1], [11, 16, 1, 3]]
0.19678432870520834 0 30 12 0.1
0.07254150050499064 50 30 12 0.1
0.00664617296484971 100 30 12 0.1
0.0011143148940565054 150 30 12 0.1
Done Training
13.183386974695164 0 60 2 1
1.345569977235142 50 60 2 1
0.11091194424113236 100 60 2 1
0.009143291527056494 150 60 2 1
Done Training
0.10077089267717504 0 40 17 0.01
0.0017814004961579383 50 40 17 0.01
0.0011048752693948324 100 40 17 0.01
0.0011351563098284973 150 40 17 0.01
Done Training
0.7222730069532517 0 70 2 0.01
0.0179123236776411 50 70 2 0.01
0.0007788525772617956 100 70 2 0.01
0.0019656883862705587 150 70 2 0.01
Done Training
0.05656460846878589 0 130 16 0.001
0.0010492796368135535 50 130 16 0.001
0.0010948414717570356 100 130 16 0.001
0.0011381316888103752 150 130 16 0.001
Done Training
3.4057557213349114 0 120 17 0.1
0.2576788832271136 50 120 17 0.1
0.019249334019393997 100 120 17 0.1
0.0016799269655981604 150 120 17

0.0009136542937108785 50 130 8 0.001
0.0010708119905246316 100 130 8 0.001
0.001087199043254314 150 130 8 0.001
Done Training
library
this is the best: [6, 1, 2, 1]
these are bitwise: ['00110'] and ['00100']
these are bitwise: ['00110', '00011'] and ['00100', '00001']
these are bitwise: ['00110', '00011', '11'] and ['00100', '00001', '10']
these are bitwise: ['00110', '00011', '11', '01'] and ['00100', '00001', '10', '11']
Current population is: [[6, 1, 2, 1], [4, 3, 3, 3], [12, 7, 3, 1], [6, 1, 2, 2], [6, 3, 3, 1], [4, 1, 2, 3]]
library
library
library
library
library
0.45527428037537876 0 50 2 0.01
0.006366203996643855 50 50 2 0.01
0.0010039559642525087 100 50 2 0.01
0.0008313587564313747 150 50 2 0.01
Done Training
this is the best: [6, 1, 2, 1]
these are bitwise: ['00100'] and ['00110']
these are bitwise: ['00100', '00011'] and ['00110', '00001']
these are bitwise: ['00100', '00011', '11'] and ['00110', '00001', '10']
these are bitwise: ['00100', '00011', '11', '01'] and ['00110', 

0.0033798347337650335 100 150 1 0.01
0.0009636453992534312 150 150 1 0.01
Done Training
0.10738033683765487 0 60 2 0.001
0.0069377451693615755 50 60 2 0.001
0.0007568845629232736 100 60 2 0.001
0.0007641343266873016 150 60 2 0.001
Done Training
this is the best: [15, 1, 3, 3]
these are bitwise: ['01101'] and ['00111']
these are bitwise: ['01101', '00001'] and ['00111', '00001']
these are bitwise: ['01101', '00001', '11'] and ['00111', '00001', '11']
these are bitwise: ['01101', '00001', '11', '10'] and ['00111', '00001', '11', '01']
Current population is: [[15, 1, 3, 3], [5, 1, 3, 0], [6, 1, 2, 1], [4, 3, 3, 3], [12, 1, 3, 2], [7, 1, 3, 3]]
library
library
library
library
0.19212066453136745 0 130 2 0.001
0.005031098940509318 50 130 2 0.001
0.0010485839128351678 100 130 2 0.001
0.0008467942877841459 150 130 2 0.001
Done Training
0.03148872787914959 0 80 2 0.001
0.002257218810986779 50 80 2 0.001
0.0010524751518096707 100 80 2 0.001
0.0007312777470832583 150 80 2 0.001
Done Training
thi

0.061093217240906515 100 150 2 0.1
0.0039296943209191386 150 150 2 0.1
Done Training
0.21026738881246834 0 150 4 0.001
0.002492086333305657 50 150 4 0.001
0.0009035134794969201 100 150 4 0.001
0.0009067091333400382 150 150 4 0.001
Done Training
this is the best: [14, 1, 3, 3]
these are bitwise: ['01111'] and ['01110']
these are bitwise: ['01111', '00001'] and ['01110', '00001']
these are bitwise: ['01111', '00001', '11'] and ['01110', '00001', '11']
these are bitwise: ['01111', '00001', '11', '11'] and ['01110', '00001', '11', '11']
Current population is: [[14, 1, 3, 3], [15, 1, 3, 3], [15, 1, 3, 3], [15, 1, 3, 3], [17, 17, 1, 2], [14, 1, 3, 3]]
library
library
library
library
1.2502070515142865 0 180 18 0.1
1.6097881044886078 50 180 18 0.1
0.11281647078052236 100 180 18 0.1
0.009039675206235468 150 180 18 0.1
Done Training
library
this is the best: [14, 1, 3, 3]
these are bitwise: ['01110'] and ['01110']
these are bitwise: ['01110', '00001'] and ['01110', '00001']
these are bitwise: [

1.800636854026392 0 150 2 0.01
0.0428305661737808 50 150 2 0.01
0.004177057270430383 100 150 2 0.01
0.0012628991369624824 150 150 2 0.01
Done Training
this is the best: [14, 1, 3, 3]
these are bitwise: ['01110'] and ['01110']
these are bitwise: ['01110', '00001'] and ['01110', '00001']
these are bitwise: ['01110', '00001', '11'] and ['01110', '00001', '11']
these are bitwise: ['01110', '00001', '11', '11'] and ['01110', '00001', '11', '11']
Current population is: [[14, 1, 3, 3], [14, 1, 3, 3], [14, 1, 3, 3], [14, 1, 3, 3], [10, 17, 3, 1], [14, 1, 3, 3]]
library
library
library
library
0.09174180484395672 0 110 18 0.001
0.0023457876648252914 50 110 18 0.001
0.0010749955682068481 100 110 18 0.001
0.0011416175598866782 150 110 18 0.001
Done Training
library
this is the best: [14, 1, 3, 3]
these are bitwise: ['01110'] and ['01110']
these are bitwise: ['01110', '00001'] and ['01110', '00001']
these are bitwise: ['01110', '00001', '11'] and ['01110', '00001', '11']
these are bitwise: ['01110

0.001184001172043251 100 130 18 0.001
0.0010815668614240117 150 130 18 0.001
Done Training
library
this is the best: [14, 1, 3, 3]
these are bitwise: ['01110'] and ['01110']
these are bitwise: ['01110', '00001'] and ['01110', '00001']
these are bitwise: ['01110', '00001', '11'] and ['01110', '00001', '11']
these are bitwise: ['01110', '00001', '11', '11'] and ['01110', '00001', '11', '11']
Current population is: [[14, 1, 3, 3], [14, 1, 3, 3], [14, 1, 3, 3], [14, 1, 3, 3], [17, 9, 3, 3], [14, 9, 3, 3]]
library
library
library
library
0.07115439008438627 0 180 10 0.001
0.0028089880007229695 50 180 10 0.001
0.001232661285492079 100 180 10 0.001
0.0011252510798537123 150 180 10 0.001
Done Training
library
this is the best: [14, 1, 3, 3]
these are bitwise: ['01110'] and ['01110']
these are bitwise: ['01110', '00001'] and ['01110', '00001']
these are bitwise: ['01110', '00001', '11'] and ['01110', '00001', '11']
these are bitwise: ['01110', '00001', '11', '11'] and ['01110', '00001', '11', '

0.000766707778115462 150 110 4 0.001
Done Training
0.21302144920244956 0 30 10 0.001
0.00848199883191359 50 30 10 0.001
0.0011724444026676192 100 30 10 0.001
0.001119887653479706 150 30 10 0.001
Done Training
this is the best: [10, 1, 3, 1]
these are bitwise: ['01010'] and ['01010']
these are bitwise: ['01010', '00001'] and ['01010', '00001']
these are bitwise: ['01010', '00001', '11'] and ['01010', '00001', '11']
these are bitwise: ['01010', '00001', '11', '01'] and ['01010', '00001', '11', '01']
Current population is: [[10, 1, 3, 1], [10, 1, 3, 1], [10, 1, 3, 1], [10, 1, 3, 1], [12, 1, 3, 3], [10, 17, 3, 0]]
library
library
library
library
library
0.04537224143308044 0 110 18 0.001
0.0013505136589165344 50 110 18 0.001
0.0011376934100203533 100 110 18 0.001
0.004066990265155182 150 110 18 0.001
Done Training
this is the best: [10, 1, 3, 1]
these are bitwise: ['01010'] and ['01010']
these are bitwise: ['01010', '00001'] and ['01010', '00001']
these are bitwise: ['01010', '00001', '11'

0.0009071214645441601 100 30 18 0.001
0.0011475408118008503 150 30 18 0.001
Done Training
0.10084664233985828 0 110 2 0.001
0.008268993859757337 50 110 2 0.001
0.0011857408494305398 100 110 2 0.001
0.0010535272868366068 150 110 2 0.001
Done Training
this is the best: [10, 1, 3, 1]
these are bitwise: ['01010'] and ['01010']
these are bitwise: ['01010', '00001'] and ['01010', '00001']
these are bitwise: ['01010', '00001', '11'] and ['01010', '00001', '11']
these are bitwise: ['01010', '00001', '11', '01'] and ['01010', '00001', '11', '01']
Current population is: [[10, 1, 3, 1], [10, 1, 3, 1], [10, 1, 3, 1], [10, 1, 3, 1], [10, 0, 3, 0], [10, 1, 3, 1]]
library
library
library
library
0.04522042591155698 0 110 1 0.001
0.001889771078901242 50 110 1 0.001
0.0009697702106192508 100 110 1 0.001
0.0008141728566100524 150 110 1 0.001
Done Training
library
this is the best: [10, 1, 3, 1]
these are bitwise: ['01010'] and ['01010']
these are bitwise: ['01010', '00001'] and ['01010', '00001']
these 

0.1567169486219478 0 120 2 0.001
0.005396343570291696 50 120 2 0.001
0.0010617512178544837 100 120 2 0.001
0.0005323449941590199 150 120 2 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [10, 1, 3, 1], [10, 1, 3, 1], [11, 1, 3, 3], [17, 5, 3, 1]]
library
library
library
library
0.10508633681472737 0 120 2 0.001
0.005747504784771428 50 120 2 0.001
0.0011011766809168543 100 120 2 0.001
0.000698344518672934 150 120 2 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise

0.0024825568713309786 50 120 18 0.001
0.0012465152495319293 100 120 18 0.001
0.0011361317492642503 150 120 18 0.001
Done Training
1.9877867705407948 0 120 10 0.1
0.7907848637930313 50 120 10 0.1
0.03957478934435203 100 120 10 0.1
0.0038384554020413865 150 120 10 0.1
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 0], [11, 0, 3, 3]]
library
library
library
library
0.10088110239682813 0 120 2 0.001
0.0031650015060549516 50 120 2 0.001
0.001333614844017923 100 120 2 0.001
0.0011785174036343775 150 120 2 0.001
Done Training
0.030618586877430205 0 120 1 0.001
0.006510276059917756 50 120 1 0.001
0.0020262667391732787 100 120 1 0.001
0.00135498

0.004375017628399608 50 140 4 0.001
0.000897262215332118 100 140 4 0.001
0.0007027209650669221 150 140 4 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 9, 2, 1], [11, 1, 3, 1]]
library
library
library
library
0.5617638040992805 0 120 10 0.01
0.01716759625228062 50 120 10 0.01
0.0015655933821564173 100 120 10 0.01
0.0010802852254258697 150 120 10 0.01
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['0101

0.001506190614223227 50 160 18 0.001
0.0011922359817880385 100 160 18 0.001
0.0011266786635786106 150 160 18 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 8, 3, 1], [11, 3, 3, 1]]
library
library
library
library
0.08507814147756063 0 120 9 0.001
0.0016640890117398585 50 120 9 0.001
0.001212554771572783 100 120 9 0.001
0.0011079516127162066 150 120 9 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and 

2.3739964693535445 0 120 18 1
2.951217790339488 50 120 18 1
0.3914650092728144 100 120 18 1
0.02773907152218742 150 120 18 1
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [15, 1, 1, 1], [15, 17, 3, 1]]
library
library
library
library
1.4349937059901143 0 160 2 0.1
1.049914845578917 50 160 2 0.1
0.06588029210935659 100 160 2 0.1
0.005808006929284083 150 160 2 0.1
Done Training
0.06996315649281466 0 160 18 0.001
0.0011232351814839366 50 160 18 0.001
0.0011774548580053257 100 160 18 0.001
0.001136275365532499 150 160 18 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'

0.2356711981452759 50 110 10 0.1
0.02094056839806564 100 110 10 0.1
0.00217264897610693 150 110 10 0.1
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [3, 9, 1, 1], [11, 1, 3, 1]]
library
library
library
library
1.3166614847037101 0 40 10 0.1
0.08779714529197534 50 40 10 0.1
0.00608754377409452 100 40 10 0.1
0.0011728963554787247 150 40 10 0.1
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001'

0.0010979757293350136 150 100 4 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [15, 1, 3, 1], [11, 0, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
thes

3.7146474552039717 50 120 2 1
0.1292504250890195 100 120 2 1
0.020834099238777732 150 120 2 1
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 5, 3, 1], [11, 3, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 3, 3, 2], [3, 3, 3, 1]]
library
library
libra

0.0011102316635838952 100 110 10 0.001
0.0010835670747775374 150 110 10 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 9, 3, 1], [15, 5, 3, 1]]
library
library
library
library
library
0.04280166826005064 0 160 6 0.001
0.003173708709814036 50 160 6 0.001
0.0010662730871157581 100 160 6 0.001
0.001087451861313677 150 160 6 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current

0.8967600250264256 50 160 4 0.1
0.06200144076486851 100 160 4 0.1
0.0025175066486651885 150 160 4 0.1
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [3, 1, 2, 3]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1]]
library
library
libra

0.0011829473960693394 150 180 2 0.01
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 0], [3, 1, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 5, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these 

0.030437866914463308 50 110 18 0.01
0.002252694282003277 100 110 18 0.01
0.02770918087970896 150 110 18 0.01
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [9, 11, 3, 1], [10, 11, 3, 2]]
library
library
library
library
0.08996313305997926 0 100 12 0.001
0.0024842297889691185 50 100 12 0.001
0.0010733959891614945 100 100 12 0.001
0.001114199264649848 150 100 12 0.001
Done Training
0.08126907539249213 0 110 12 0.001
0.0012352536583328806 50 110 12 0.001
0.0011503156113530323 100 110 12 0.001
0.0011040368218632496 150 110 12 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['010

0.3508853641650262 50 120 10 0.1
0.018307345045827452 100 120 10 0.1
0.0026142349720912443 150 120 10 0.1
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 13, 3, 1], [11, 1, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [9, 5, 3, 1], [17, 8, 1, 1]]
library


0.0009016323175211797 150 180 2 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 3, 3, 3], [11, 1, 3, 1]]
library
library
library
library
0.028261240616839458 0 120 4 0.001
0.0012825786566178098 50 120 4 0.001
0.0009850842120999624 100 120 4 0.001
0.0011277793066045451 150 120 4 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1

Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 0], [15, 0, 3, 1]]
library
library
library
library
library
0.1833989640028122 0 160 1 0.001
0.003314825050964346 50 160 1 0.001
0.0008265099140096797 100 160 1 0.001
0.0007687240954159772 150 160 1 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [

0.02661612331067924 100 20 2 1
0.0032248631099825033 150 20 2 1
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 2, 1], [17, 1, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [17, 1, 3, 1]]
library
library
library
library
library
library
this is th

0.0017274607407053565 50 120 8 0.001
0.0012034030298956606 100 120 8 0.001
0.0010584191515211991 150 120 8 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 9, 2, 0], [9, 1, 3, 1]]
library
library
library
library
0.27700608399583826 0 120 10 0.01
0.02690667414921439 50 120 10 0.01
0.0021585524643387166 100 120 10 0.01
0.00123593977492559 150 120 10 0.01
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] an

0.0012533231139190426 100 160 4 0.001
0.0009765177424098494 150 160 4 0.001
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [7, 1, 0, 1], [17, 1, 3, 1]]
library
library
library
library
4.92228693651563 0 80 2 1
3.345845801707861 50 80 2 1
0.08884988825559431 100 80 2 1
0.014272648778530522 150 80 2 1
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1

0.009729173651197643 50 40 2 0.001
0.001018222713256746 100 40 2 0.001
0.0010530326612721076 150 40 2 0.001
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 9, 3, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [15, 1, 3, 1]]
library
librar

0.022823475383925006 50 180 10 0.01
0.002278506814389585 100 180 10 0.01
0.001177880915929665 150 180 10 0.01
Done Training
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [3, 1, 2, 1]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 3], [9, 17, 3, 1]]
libra

0.004462861549090805 50 30 4 0.01
0.0010408110653804023 100 30 4 0.01
0.0008928532621470068 150 30 4 0.01
Done Training
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 3]]
library
library
library
library
library
library
this is the best: [11, 1, 3, 1]
these are bitwise: ['01011'] and ['01011']
these are bitwise: ['01011', '00001'] and ['01011', '00001']
these are bitwise: ['01011', '00001', '11'] and ['01011', '00001', '11']
these are bitwise: ['01011', '00001', '11', '01'] and ['01011', '00001', '11', '01']
Current population is: [[11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [11, 1, 3, 1], [17, 1, 3, 1]]
library
library


0.0011631427245726294 50 120 18 0.001
0.0011413828369225682 100 120 18 0.001
0.0011291778628217575 150 120 18 0.001


KeyboardInterrupt: 