In [1]:
import json 
from netCDF4 import Dataset
import numpy as np
from scipy.spatial.distance import pdist
import random
from sklearn.model_selection import train_test_split
import NeuralNetwork
from SimulatedAnnealing import SimulatedAnnealing

import math 
with open('configSA.json') as f:
  print(f)
  config = json.loads(f.read())
import random

print(config)

<_io.TextIOWrapper name='configSA.json' mode='r' encoding='UTF-8'>
{'config': {'debug': 'on', 'database': {'file': 'db.dat', 'properties': ['energy', 'gradient'], 'crdmode': 'cartesian', 'timestamp': '2021-04-23T18:25:43.511Z', 'mode': 'ab-initio', 'ab-initio': {'exe': 'QChem.exe', 'chg': 0, 'mult': 1, 'exchange': 'pbe0', 'basis': 'cc-pvdz', 'max_scf_cycles': 500, 'xc_grid': '000075000302', 'mem_static': 4000, 'mem_total': 16000, 'sym_ignore': True, 'set_iter': 50, 'input_bohr': True}}, 'neural_network': {'epochs': 1000, 'epoch_step': 50, 'logging_file': 'logfile.txt', 'plotting_file': 'plottingfile.txt', 'optimizer': 'adam', 'activation': 'tanh', 'loss_function': 'MSE', 'model_filename': 'Network.pt'}, 'simulated_annealing': {'hiddenlayer_size': [10, 200, 10], 'validation_ratio': 0.1, 'hiddenlayer_number': [1, 20, 1], 'learning_rates': [1, 0.1, 0.01, 0.001, 0.0001], 'batch_size': [32, 64, 128, 256, 512], 'iterations': 2000, 'temperature': 0.01}}}


In [2]:

lowest_error, best_network = math.inf, None
sizebounds = config['config']['simulated_annealing']['hiddenlayer_size']
layerbounds = config['config']['simulated_annealing']['hiddenlayer_number']
learningbounds = config['config']['simulated_annealing']['learning_rates']


print(random.randint(sizebounds[0],sizebounds[1]))
print(random.choice(learningbounds))

#for n in range(self.config['config']['simulated_annealing']['iterations']) :

    



82
0.1


In [3]:
database = 'db.dat'
data = Dataset(database, mode='r')
if config['config']["database"]["crdmode"] == "cartesian":
    dbset = np.copy(data['crd'])
    coordinatesout = []
    for j,i in enumerate(dbset):
        if j == 0:
            coordinatesout = [pdist(i)]
        else:
            coordinatesout = np.concatenate((coordinatesout,[pdist(i)]))
            
energyout =np.copy(data['energy'])-np.amin(data['energy'])     
print(coordinatesout)
print(energyout)



[[2.77941757 2.76440917 4.84697076]
 [2.76698152 2.76900611 4.83948085]
 [2.75691651 2.77593716 4.83429377]
 [2.74938863 2.78508657 4.83143719]
 [2.74453164 2.79630852 4.83089482]
 [2.74244372 2.80942972 4.83260669]
 [2.7431851  2.82425238 4.83647096]
 [2.74677709 2.8405571  4.84234703]
 [2.75320254 2.85810566 4.8500602 ]
 [2.76240746 2.87664359 4.85940741]
 [2.77430386 2.89590254 4.87016427]]
[[1.30026000e-05 1.38476884e-01 1.58162384e-01]
 [0.00000000e+00 1.39150584e-01 1.58955644e-01]
 [2.89870001e-05 1.39480344e-01 1.59147334e-01]
 [8.40001001e-05 1.39443554e-01 1.58714964e-01]
 [1.63652300e-04 1.39037264e-01 1.57668304e-01]
 [2.81846500e-04 1.38279024e-01 1.56049534e-01]
 [4.67269800e-04 1.37206234e-01 1.53931434e-01]
 [7.61541000e-04 1.35874014e-01 1.51413464e-01]
 [1.21603860e-03 1.34351604e-01 1.48616114e-01]
 [1.88761530e-03 1.32717424e-01 1.45673914e-01]
 [2.83360780e-03 1.31053354e-01 1.42727624e-01]]


In [4]:
coordinates, val_coordinates, output, val_output = train_test_split(coordinatesout, energyout , test_size=config['config']['simulated_annealing']['validation_ratio'])

print(output,val_output)
print(coordinates, val_coordinates)


[[1.63652300e-04 1.39037264e-01 1.57668304e-01]
 [1.30026000e-05 1.38476884e-01 1.58162384e-01]
 [1.21603860e-03 1.34351604e-01 1.48616114e-01]
 [2.83360780e-03 1.31053354e-01 1.42727624e-01]
 [7.61541000e-04 1.35874014e-01 1.51413464e-01]
 [8.40001001e-05 1.39443554e-01 1.58714964e-01]
 [4.67269800e-04 1.37206234e-01 1.53931434e-01]
 [1.88761530e-03 1.32717424e-01 1.45673914e-01]
 [2.89870001e-05 1.39480344e-01 1.59147334e-01]] [[0.         0.13915058 0.15895564]
 [0.00028185 0.13827902 0.15604953]]
[[2.74453164 2.79630852 4.83089482]
 [2.77941757 2.76440917 4.84697076]
 [2.75320254 2.85810566 4.8500602 ]
 [2.77430386 2.89590254 4.87016427]
 [2.74677709 2.8405571  4.84234703]
 [2.74938863 2.78508657 4.83143719]
 [2.7431851  2.82425238 4.83647096]
 [2.76240746 2.87664359 4.85940741]
 [2.75691651 2.77593716 4.83429377]] [[2.76698152 2.76900611 4.83948085]
 [2.74244372 2.80942972 4.83260669]]


In [5]:
#if (any(i == 'simulated_annealing' for i in config['config'])):
#    if (any(j == 'neural_network' for j in config['config'])):
#        optimizer = SimulatedAnnealing(config,coordinates,  output,val_coordinates, val_output)
#        optimizer.run()

if (any(i == 'simulated_annealing' for i in config['config'])):
    if (any(j == 'neural_network' for j in config['config'])):
        optimizer = SimulatedAnnealing(config,coordinates,  output,val_coordinates, val_output)
        optimizer.run()
        
        
        

0.1200039369701452 0 50 18 0.001
0.006710514426376788 50 50 18 0.001
0.0033881246484374614 100 50 18 0.001
0.0031234068999201766 150 50 18 0.001
0.0031288516608743546 200 50 18 0.001
0.0031283255746651925 250 50 18 0.001
0.003128384093671232 300 50 18 0.001
0.003128377366610394 350 50 18 0.001
0.00312836551155091 400 50 18 0.001
0.00312835202415786 450 50 18 0.001
0.003128337068112501 500 50 18 0.001
0.003128320320750205 550 50 18 0.001
0.0031283013283605033 600 50 18 0.001
0.003128279471684354 650 50 18 0.001
0.003128253891239245 700 50 18 0.001
0.0031282233724843483 750 50 18 0.001
0.0031281861556328653 800 50 18 0.001
0.0031281396081894097 850 50 18 0.001
0.0031280796322718366 900 50 18 0.001
0.0031279995238403776 950 50 18 0.001
Done Training
4
16
4
0
0.1959374617438448 0 50 17 0.0001
0.08274007938723595 50 50 17 0.0001
0.007295485316775885 100 50 17 0.0001
0.003150030692430287 150 50 17 0.0001
0.0031094204132238934 200 50 17 0.0001
0.0031276248353072538 250 50 17 0.0001
0.00312640

0.0031285363924175597 350 30 16 0.001
0.0031285158043573213 400 30 16 0.001
0.0031284947689585534 450 30 16 0.001
0.0031284728894177436 500 30 16 0.001
0.003128450149255072 550 30 16 0.001
0.003128426558001326 600 30 16 0.001
0.003128402102579299 650 30 16 0.001
0.003128376741297972 700 30 16 0.001
0.0031283504018845077 750 30 16 0.001
0.00312832297856468 800 30 16 0.001
0.003128294327782544 850 30 16 0.001
0.003128264262215148 900 30 16 0.001
0.0031282325425638865 950 30 16 0.001
Done Training
new error found 0.002848341611515765 
error is: 0.002848341611515765  lowest error  )0.0002119542495488924
0.09322413554229332
4
15
3
0
0.18136683057435152 0 50 16 0.001
0.008376646895623008 50 50 16 0.001
0.003196188353045915 100 50 16 0.001
0.0031036901307201475 150 50 16 0.001
0.0031285763191250295 200 50 16 0.001
0.0031285557714773172 250 50 16 0.001
0.0031284169605468952 300 50 16 0.001
0.0031283858734447805 350 50 16 0.001
0.0031283604430963866 400 50 16 0.001
0.0031283328977733493 450 50 

KeyboardInterrupt: 